### ISSUE TITLE
律师函.jpg

### ISSUE THREAD

**Issue by fumiama** [C1enDev/C1enBot#2]
以下是[ZeroBot-Plugin](https://github.com/FloatTech/ZeroBot-Plugin)仓库的AGPL协议要求您遵守但是您尚未做到的项目，请进行修改：
- `License and copyright notice`：在显眼位置给出源仓库的地址，包括但不限于README、帮助信息等位置
- `State changes`：在显眼位置说明此仓库与源仓库的不同之处

**Comment by C1en-QwQ** [comment]
做好了
